import { Station } from '../lakes-config'

export const THUNERSEE_STATIONS: Station[] = [
  { name: 'Thun (See)', latitude: 46.754101, longitude: 7.63132, uic_ref: '8507150' },
  { name: 'Hilterfingen (See)', latitude: 46.735055, longitude: 7.657459, uic_ref: '8507151' },
  { name: 'Oberhofen am Thunersee', latitude: 46.730358, longitude: 7.667487, uic_ref: '8507152' },
  { name: 'Gunten', latitude: 46.712467, longitude: 7.700315, uic_ref: '8507153' },
  { name: 'Gwatt Deltapark (See)', latitude: 46.720495, longitude: 7.635831, uic_ref: '8507159' },
  { name: 'Spiez Schiffstation', latitude: 46.688472, longitude: 7.689885, uic_ref: '8507154' },
  { name: 'Einigen (See)', latitude: 46.709752, longitude: 7.647195, uic_ref: '8507164' },
  { name: 'Hünibach (See)', latitude: 46.743565, longitude: 7.642667, uic_ref: '8507161' },
  { name: 'Faulensee (See)', latitude: 46.675992, longitude: 7.703576, uic_ref: '8507166' },
  { name: 'Merligen (See)', latitude: 46.696364, longitude: 7.737172, uic_ref: '8507155' },
  { name: 'Beatenbucht (See)', latitude: 46.686599, longitude: 7.74602, uic_ref: '8507156' },
  { name: 'Interlaken West (See)', latitude: 46.682202, longitude: 7.850731, uic_ref: '8507169' },
  { name: 'Neuhaus (Unterseen) (See)', latitude: 46.67832, longitude: 7.815818, uic_ref: '8507158' },
  { name: 'Beatushöhlen-Sundlauenen', latitude: 46.684997, longitude: 7.789918, uic_ref: '8507157' },
  { name: 'Leissigen (See)', latitude: 46.655432, longitude: 7.770508, uic_ref: '8507167' },
  { name: 'Därligen (See)', latitude: 46.6646598, longitude: 7.8062511, uic_ref: '8507168' },
]

export const THUNERSEE_NAME_MAPPING: Record<string, string> = {
  // Basisnamen
  'Thun': 'Thun (See)',
  'Thun (See)': 'Thun (See)',
  'Hilterfingen': 'Hilterfingen (See)',
  'Hilterfingen (See)': 'Hilterfingen (See)',
  'Oberhofen am Thunersee': 'Oberhofen am Thunersee',
  'Oberhofen': 'Oberhofen am Thunersee',
  'Gunten': 'Gunten',
  'Gwatt Deltapark': 'Gwatt Deltapark (See)',
  'Gwatt Deltapark (See)': 'Gwatt Deltapark (See)',
  'Gwatt': 'Gwatt Deltapark (See)',
  'Spiez Schiffstation': 'Spiez Schiffstation',
  'Spiez': 'Spiez Schiffstation',
  'Einigen': 'Einigen (See)',
  'Einigen (See)': 'Einigen (See)',
  'Hünibach': 'Hünibach (See)',
  'Hünibach (See)': 'Hünibach (See)',
  'Faulensee': 'Faulensee (See)',
  'Faulensee (See)': 'Faulensee (See)',
  'Merligen': 'Merligen (See)',
  'Merligen (See)': 'Merligen (See)',
  'Beatenbucht': 'Beatenbucht (See)',
  'Beatenbucht (See)': 'Beatenbucht (See)',
  'Interlaken West': 'Interlaken West (See)',
  'Interlaken West (See)': 'Interlaken West (See)',
  'Neuhaus (Unterseen)': 'Neuhaus (Unterseen) (See)',
  'Neuhaus (Unterseen) (See)': 'Neuhaus (Unterseen) (See)',
  'Beatushöhlen-Sundlauenen': 'Beatushöhlen-Sundlauenen',
  'Leissigen': 'Leissigen (See)',
  'Leissigen (See)': 'Leissigen (See)',
  'Därligen': 'Därligen (See)',
  'Därligen (See)': 'Därligen (See)',

  // Zusätzliche Varianten
  'Thun See': 'Thun (See)',
  'Hilterfingen See': 'Hilterfingen (See)',
  'Oberhofen See': 'Oberhofen am Thunersee',
  'Gunten See': 'Gunten',
  'Gwatt See': 'Gwatt Deltapark (See)',
  'Spiez See': 'Spiez Schiffstation',
  'Einigen See': 'Einigen (See)',
  'Hünibach See': 'Hünibach (See)',
  'Faulensee See': 'Faulensee (See)',
  'Merligen See': 'Merligen (See)',
  'Beatenbucht See': 'Beatenbucht (See)',
  'Interlaken West See': 'Interlaken West (See)',
  'Neuhaus See': 'Neuhaus (Unterseen) (See)',
  'Leissigen See': 'Leissigen (See)',
  'Därligen See': 'Därligen (See)',

}